config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :vans do
    resources :bookings, only: [:create, :new] do
      # member do
      #   patch :accepted
      #   patch :declined
      # end
    end
    
  end
  resources :bookings, only: [] do
    member do 
      patch "accepted"
      patch "declined"
    end
  end
  # patch "bookings/:id/accepted", to: "bookings#accept"
  # patch "bookings/:id/declined", to: "bookings#declined"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
  get "profile", to: "pages#profile"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :van
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true, inclusion: { in: ["Pending", "Accepted", "Declined"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :vans, dependent: :destroy
  
  # validates :address, presence: true
  validates :email, presence: true
  validates :password, presence: true
 # validates :first_name, presence: true
 # validates :last_name, presence: true
 # validates :driving_license, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/van.rb
class Van < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  validates :nb_seats, presence: true, inclusion: { in: 1..9 }
  validates :brand, presence: true
  validates :description, presence: true
  validates :localisation, presence: true
  geocoded_by :localisation
  after_validation :geocode, if: :will_save_change_to_localisation?
  validates :photo, presence: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @booking.user = current_user
    @van = Van.find(params[:van_id])
  end

  def create
    if current_user
      @booking = Booking.new(booking_params)
      @van = Van.find(params[:van_id])
      @booking.van = @van
      @booking.user = current_user
      @booking.status = "Pending"
      if @booking.save!
        redirect_to profile_path
      else
        render :new
      end
    else
      redirect_to new_user_session_path
    end
  end

  def accepted
    @booking = Booking.find(params[:id])
    @booking.status = "Accepted"
    @booking.save
    redirect_to profile_path anchor: "booking-#{@booking.id}"
  end

  def declined
    @booking = Booking.find(params[:id])
    @booking.status = "Declined"
    @booking.save
    redirect_to profile_path anchor: "booking-#{@booking.id}"
  end

   private
  def booking_params
    params.require(:booking).permit(:start_date, :end_date )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def profile
  end
end

app/controllers/vans_controller.rb
class VansController < ApplicationController

  def index
    @vans = Van.all
    @markers = @vans.geocoded.map do |van|
      {
        lat: van.latitude,
        lng: van.longitude,
        info_window: render_to_string(partial: "info_window", locals: { van: van }),
        image_url: helpers.asset_url('van-logo.png')
      }
    end
  end

  def show
    @van = Van.find(params[:id])
  end

  def new
    @van = Van.new
  end

  def create
    if current_user
      @van = Van.new(params_van)
      @van.user = current_user

      if @van.save
        redirect_to van_path(@van)
      else
        render :new
      end
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    @van = Van.find(params[:id])
  end

  def update
    if current_user
      @van = Van.find(params[:id])
      @van.update(params_van)
      if @van.save
        redirect_to van_path(@van)
      else
        render :new
      end
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    @van = Van.find(params[:id])
    @van.destroy
    redirect_to vans_path
  end

  private

  def params_van
    params.require(:van).permit(:nb_seats, :brand, :description, :localisation, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
<h1>Dates</h1>
<%= simple_form_for([@van,@booking]) do  |f| %>
  <%= f.input :start_date, as: :string, input_html: { class: "datepicker" } %>
  <%= f.input :end_date, as: :string, input_html: { class: "datepicker" } %>
  <%= f.submit "Ask for booking", class: "btn btn-success" %>
<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VanYourLife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' unless current_page?(root_path) %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1515876305430-f06edab8282a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80);">
  <%= render 'shared/navbar' %>
  <div class="text-banner container">
    <h1>Van Your Life</h1>
    <h2><span id="banner-typed-text"></span></h2>
    <p><%= link_to "Try it now ! 😎", vans_path, class: 'btn btn-ghost mt-4' %></p>
  </div>
</div>


<footer class = "footer">
  <div class = "footer-container" >
    <div class = "icons-container">
      <p>Follow us</p>
      <div class="icons pb-3">
       <a href = "#"><i class="footer-icon fab fa-facebook-square fa-2x"></i></a>
       <a href = "#"><i class="footer-icon fab fa-instagram fa-2x"></i></a>
       <a href = "#"><i class="footer-icon fab fa-youtube fa-2x"></i></a>
      </div>
    </div>
    <p>© 2021 VanYourLife</p>
  </div>
</footer>

app/views/pages/profile.html.erb
<br>
<h1>Welcome on board !</h1>
<h2>Manage all your rentals from here</h2>

<div class="container py-5 mb-5">
  <div class="card-product">
    <%= image_tag "avatar.png", class: "avatar-bordered" %>
    <div class="card-product-infos">
      <h2><i class="fas fa-medal"></i>Super Van Host</h2>
      <h2> ⭐ 1200 commentaires </h2>
      <br>
      <h2>Yasmine</h2>
      <br>
      <h2>25 ans, habite à Lille</h2>
      <p>Passionée de voyage, j'adore utiliser mon van pour partir en vadrouille.<br>
      Très pratique, il est full <strong>équipé</strong>, que ce soit pour cuisiner, dormir ou juste s'installer dedans et vaquer à mes occupations</p>
    </div>
  </div>
</div>

<div class="container" id="bookings">
  <div class="row">
    <div class="col-12 col-lg-6">
      <h2>My booking demands</h2>
      <% current_user.bookings.each do |booking|%>

        <% van = Van.find(booking.van_id) %>
        <br>
        <div class="card mb-4" style="width: 25rem; height: 545px;">
          <br>
          <%= cl_image_tag van.photo.key, height: 300, width: 400, crop: :fill, class: "card-img-top", alt: "..." %>
          <div class="card-body">
            <div class="card-title">
              <p>💡 <%= van.description %></p>
            </div>
            <div class="card-text text-center">
              <p>Brand: <%= van.brand %></p>
              <p>Seats: <%=van.nb_seats %></p>
              <p>Location: <%=van.localisation %></p>
              <p>Status: <%=booking.status %></p>
            </div>
          </div>
        </div>
      <% end  %>
    </div>

    <div class="col-12 col-lg-6">
      <h2>They want to book your van</h2>
      <br>
      <% current_user.vans.each do |van| %>
        <% @bookings = Booking.where(van: van) %>
        <% @bookings.each do |booking| %>
          <% Van.find(booking.van_id).description %>
          <div class="card mb-4" id="booking-<%= booking.id %>"style="width: 25rem; height: 545px;">
            <br>
             <%= cl_image_tag van.photo.key, height: 280, width: 400, crop: :fill, class: "card-img", alt: "..." %>
            <br>
            <div class="card-body">
              <img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm"/>
              <p>👋 "Hi, please, I'd like to rent your van"</p>
              <p>from <%=booking.start_date %> to <%=booking.end_date %></p></p>
            </div>
            <% if booking.status == "Accepted"  %>
              <p class="btn btn-success">ACCEPTED</p>
            <% elsif booking.status == "Declined"  %>
              <p class="btn btn-warning">DECLINED</p>
            <% else  %>
              <%=link_to 'ACCEPTED', accepted_booking_path(booking), method: :patch, class:"btn btn-success" %>
              <%=link_to 'DECLINED', declined_booking_path(booking), method: :patch, class:"btn btn-warning" %>
            <% end  %>
            <br>
            <br>
          </div>
        <% end %>
      <% end %>
      <br>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class=" <%= "transparent" if current_page?(root_path) %> navbar navbar-expand-sm navbar-lewagon">
  <%= link_to root_path	, class: "navbar-brand" do %>
    <%= image_tag "van-logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Lease your van",new_van_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Profile",profile_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My bookings", profile_path(:anchor => "bookings"), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://previews.123rf.com/images/tmricons/tmricons1707/tmricons170700613/81207214-ouverture-de-session-du-signe-bouton-de-d%C3%A9connexion-.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "btn btn-secondary btn-sm" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/vans/_form.html.erb
<div class="container">
  <%= simple_form_for(@van) do |f| %>
    <%= f.input :nb_seats %>
    <%= f.input :brand %>
    <%= f.input :description %>
    <%= f.input :localisation %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class:"btn btn-ghost mt-4" %>
  <% end %>
</div>

app/views/vans/_info_window.html.erb
<h2><%= van.description %></h2>
<p><%= van.localisation %></p>

app/views/vans/edit.html.erb
<div class="mt-5 mb-4">
  <h1>Edit your van description</h1>
  <h2>Don't forget that awesome solar shower you just build !</h2>
</div>
<div class="py-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.wallpapertip.com/wmimgs/31-313126_road-12-bridges-roads-photography-desktop-wallpapers-road.jpg)" >
  <div class="newform">
      <%= render "form", van: @van %>
  </div>
</div>

app/views/vans/index.html.erb
<div class="mt-5">
  <h1>Discover our finest selection of vans !</h1>
</div>

<div class="container py-5">
  <div class="row px-3">
    <div class="col-12 justify-content-center mb-5" id="map"
      style="width: 100%; height: 400px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <div class="row">
    <% @vans.each do |van| %>
      <div class="col-12 col-lg-4">
        <div class="card-category mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path van.photo.key, height: 300, width: 400, crop: :fill %>')">
          <%= link_to van.localisation, van_path(van) %>
          <% if van.user == current_user %>
            <%= link_to "+", van_path(van), method: :delete, data: {confirm: "Are you sure"}, class: "card-remove-link" %>
          <%end%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/vans/new.html.erb
<div class="mt-5 mb-4">
  <h1>Describe your van</h1>
  <h2>Share your lifestyle with other interesting people and start making money !</h2>
</div>
<div class="py-5" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://wallpaperaccess.com/full/1079100.jpg)" >
  <div class="newform">
      <%= render "form", van: @van %>
  </div>
</div>

app/views/vans/show.html.erb
<div>
<br>
<h1><%= @van.brand %></h1>
</div>
<div class="container py-3 mb-4">
  <div class="card-trip mb-4">
   <%= cl_image_tag @van.photo.key, crop: :fill %>
      <div class="card-trip-infos py-5 mb-4">
        <div>
          <br>
          <h2>Location: <%= @van.localisation %></h2>
          <br>
          <p> <%= @van.description %></p>
          <div class="d-flex mt-4">
            <%= link_to "Book this one", new_van_booking_path(@van), class:"btn btn-success mr-2"%>
            <%= link_to "Back to list", vans_path, class:"btn btn-secondary ml-2 mr-2"%>
            <% if @van.user == current_user %>
              <%= link_to "Update", edit_van_path(@van), class:"btn btn-warning ml-2 mr-2"%>
              <%= link_to "Delete", van_path(@van), method: :delete, data: {confirm: "Are you sure"}, class:"btn btn-danger ml-2 "%>
            <%end%>
          </div>
        </div>
          <p>number of seats: <%= @van.nb_seats %></p>
      </div>
  </div>
</div>